class Bubble{
    constructor({x=0,y=0,vx=-10,vy=-10,fx=0.1,fy=0.1,r=50,min=[true,false],minx=-0.5,miny=0.1,
    col="100,100,100"}){
      this.x=x;
      this.y=y;
      this.vx=vx;
      this.vy=vy;
      this.r=r;
      this.col=col;
      this.fx=fx;
      this.fy=fy;
      this.min=min;
      this.minx=minx;
      this.miny=miny;
      this.opacity=0.2;
    }
    draw(){
      backctx.fillStyle="rgba("+this.col+","+this.opacity+")";
      backctx.beginPath();
      backctx.arc(this.x,this.y,this.r,0,Math.PI*2);
      backctx.fill();
    }
    move(){
      this.x+=this.vx;
      this.y+=this.vy;
      this.vx=Math[this.min[0]?"min":"max"](this.vx+this.fx,this.minx);
      this.vy=Math[this.min[1]?"min":"max"](this.vy+this.fy,this.miny);
    }
  }